export const orderByCustomer =[
    {
        'Order Id':'10121',
        'Order No':'1',
        Service:'Cleaning',
        Partner:'Meet',
        'Partner Id':'101',
        'Commission Type':'Global',
        'Commission Amount':'250',
        Amount:'1200',
        Status:'Fulfilled',
    },
    {
        'Order Id':'10122',
        'Order No':'2',
        Service:'Mechanical',
        Partner:'Joshna',
        'Partner Id':'102',
        'Commission Type':'Service level',
        'Commission Amount':'400',
        Amount:'4200',
        Status:'Pending',
    },
    {
        'Order Id':'10123',
        'Order No':'3',
        Service:'Cleaning',
        Partner:'Meet',
        'Partner Id':'101',
        'Commission Type':'Negotiated',
        'Commission Amount':'100',
        Amount:'1000',
        Status:'Pending', 
    },
    {
        'Order Id':'10124',
        'Order No':'4',
        Service:'Electrical',
        Partner:'Kenil',
        'Partner Id':'104',
        'Commission Type':'Global',
        'Commission Amount':'300',
        Amount:'2500',
        Status:'Pending',
    },
    {
        'Order Id':'10125',
        'Order No':'5',
        Service:'Plumbing',
        Partner:'Krishna',
        'Partner Id':'105',
        'Commission Type':'Global',
        'Commission Amount':'100',
        Amount:'600',
        Status:'Fulfilled',
    },
    {
        'Order Id':'10126',
        'Order No':'6',
        Service:'Cleaning',
        Partner:'Sneha',
        'Partner Id':'103',
        'Commission Type':'Negotiated',
        'Commission Amount':'50',
        Amount:'500',
        Status:'Pending',
    },
    {
        'Order Id':'10127',
        'Order No':'7',
        Service:'Plumbing',
        Partner:'Joshna',
        'Partner Id':'102',
        'Commission Type':'Global',
        'Commission Amount':'250',
        Amount:'2000',
        Status:'Pending',
    }
]
export const orderOfPartner =[
    {
        'Order Id':'10121',
        'Order No':'1',
        Service:'Cleaning',
        Customer:'Meet',
        'Customer Id':'101',
        'Commission Type':'Global',
        'Commission Amount':'250',
        Amount:'1200',
        Status:'Fulfilled',
    },
    {
        'Order Id':'10122',
        'Order No':'2',
        Service:'Mechanical',
        Customer:'Joshna',
        'Customer Id':'102',
        'Commission Type':'Service level',
        'Commission Amount':'400',
        Amount:'4200',
        Status:'Pending',
    },
    {
        'Order Id':'10123',
        'Order No':'3',
        Service:'Cleaning',
        Customer:'Meet',
        'Customer Id':'101',
        'Commission Type':'Negotiated',
        'Commission Amount':'100',
        Amount:'1000',
        Status:'Pending',
    },
    {
        'Order Id':'10124',
        'Order No':'4',
        Service:'Electrical',
        Customer:'Kenil',
        'Customer Id':'104',
        'Commission Type':'Global',
        'Commission Amount':'300',
        Amount:'2500',
        Status:'Pending',
    },
    {
        'Order Id':'10125',
        'Order No':'5',
        Service:'Plumbing',
        Customer:'Krishna',
        'Customer Id':'105',
        'Commission Type':'Global',
        'Commission Amount':'100',
        Amount:'600',
        Status:'Fulfilled',
    },
    {
        'Order Id':'10126',
        'Order No':'6',
        Service:'Cleaning',
        Customer:'Sneha',
        'Customer Id':'103',
        'Commission Type':'Negotiated',
        'Commission Amount':'50',
        Amount:'500',
        Status:'Pending',
    },
    {
        'Order Id':'10127',
        'Order No':'7',
        Service:'Plumbing',
        Customer:'Joshna',
        'Customer Id':'102',
        'Commission Type':'Global',
        'Commission Amount':'250',
        Amount:'2000',
        Status:'Pending',
    }
]
export const allOrders=[
    {
        id: "1",
        thead: [
            {name:'Order Id',sort:true},
            {name:'Order No',sort:true},
            {name:'Service',sort:true},
            {name:'Customer',sort:false},
            {name:'Partner',sort:true},
            {name:'Commission Type',sort:false},
            {name:'Commission Amount',sort:true},
            {name:'Amount',sort:true},
            {name:'Status',sort:false},
        ],
        tbody: [
            {
                'Order Id':'10121',
                'Order No':'1',
                Service:'Cleaning',
                Customer:'Meet',
                'Customer Id':'101',
                Partner:'Meet',
                'Partner Id':'102',
                'Commission Type':'Global',
                'Commission Amount':'250',
                Amount:'1200',
                Status:'Fulfilled',
            },
            {
                'Order Id':'10122',
                'Order No':'2',
                Service:'Mechanical',
                Customer:'Joshna',
                'Customer Id':'102',
                Partner:'Kenil',
                'Partner Id':'104',
                'Commission Type':'Service level',
                'Commission Amount':'400',
                Amount:'4200',
                Status:'Pending',
            },
            {
                'Order Id':'10123',
                'Order No':'3',
                Service:'Cleaning',
                Customer:'Meet',
                'Customer Id':'101',
                Partner:'Joshna',
                'Partner Id':'101',
                'Commission Type':'Negotiated',
                'Commission Amount':'100',
                Amount:'1000',
                Status:'Pending',
            },
            {
                'Order Id':'10124',
                'Order No':'4',
                Service:'Electrical',
                Customer:'Kenil',
                'Customer Id':'104',
                Partner:'Sneha',
                'Partner Id':'105',
                'Commission Type':'Global',
                'Commission Amount':'300',
                Amount:'2500',
                Status:'Pending',
            },
            {
                'Order Id':'10125',
                'Order No':'5',
                Service:'Plumbing',
                Customer:'Krishna',
                'Customer Id':'105',
                Partner:'Ruta',
                'Partner Id':'103',
                'Commission Type':'Global',
                'Commission Amount':'100',
                Amount:'600',
                Status:'Fulfilled',
            },
            {
                'Order Id':'10126',
                'Order No':'6',
                Service:'Cleaning',
                Customer:'Sneha',
                'Customer Id':'103',
                Partner:'Hari',
                'Partner Id':'101',
                'Commission Type':'Negotiated',
                'Commission Amount':'50',
                Amount:'500',
                Status:'Pending',
            },
            {
                'Order Id':'10127',
                'Order No':'7',
                Service:'Plumbing',
                Customer:'Joshna',
                'Customer Id':'102',
                Partner:'Meet',
                'Partner Id':'102',
                'Commission Type':'Global',
                'Commission Amount':'250',
                Amount:'2000',
                Status:'Pending',
            }
        ]
    }
]
export const singleOrder = {
    orderNo:'101',
    Service:'Cleaning',
    Customer:'Meet',
    partner:'Joshna',
    commisionTpye:'Global',
    commisionAmt:'120',
    status:'Fulfilled',
    amount:'1200',
    category:'Painting',
    subCategory:'Car Painting'
}