
//admin types
export const ADMIN_API = 'ADMIN_API'
export const ADMIN_API_REQUEST = 'ADMIN_API_REQUEST'
export const ADMIN_API_SUCCESS = 'ADMIN_API_SUCCESS'
export const ADMIN_API_ERROR = 'ADMIN_API_ERROR'

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR'

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_FORGOT_PASSWORD_SUCCESS = 'ADMIN_FORGOT_PASSWORD_SUCCESS'
export const ADMIN_FORGOT_PASSWORD_ERROR = 'ADMIN_FORGOT_PASSWORD_ERROR'

export const ADMIN_FORGOT_PASSWORD_OTP_SUCCESS = 'ADMIN_FORGOT_PASSWORD_OTP_SUCCESS'
export const ADMIN_FORGOT_PASSWORD_OTP_ERROR = 'ADMIN_FORGOT_PASSWORD_OTP_ERROR'

export const ADMIN_RESET_PASSWORD_SUCCESS = 'ADMIN_RESET_PASSWORD_SUCCESS'
export const ADMIN_RESET_PASSWORD_ERROR = 'ADMIN_RESET_PASSWORD_ERROR'

export const ADMIN_CHANGE_PASSWORD_SUCCESS = 'ADMIN_CHANGE_PASSWORD_SUCCESS'
export const ADMIN_CHANGE_PASSWORD_ERROR = 'ADMIN_CHANGE_PASSWORD_ERROR'

// Customer 
export const ADMIN_CUSTOMER_LISTING_SUCCESS = 'CUSTOMER_LISTING_SUCCESS'
export const ADMIN_CUSTOMER_LISTING_FAIL = 'CUSTOMER_LISTING_FAIL'

// Category
export const ADMIN_CATEGORY_LISTING_SUCCESS = 'ADMIN_CATEGORY_LISTING_SUCCESS'
export const ADMIN_CATEGORY_LISTING_FAIL = 'ADMIN_CATEGORY_LISTING_FAIL'

export const ADMIN_CATEGORY_ADD_SUCCESS = 'ADMIN_CATEGORY_ADD_SUCCESS'
export const ADMIN_CATEGORY_ADD_FAIL = 'ADMIN_CATEGORY_ADD_FAIL'

export const ADMIN_CATEGORY_EDIT_SUCCESS = 'ADMIN_CATEGORY_EDIT_SUCCESS'
export const ADMIN_CATEGORY_EDIT_FAIL = 'ADMIN_CATEGORY_EDIT_FAIL'

export const ADMIN_CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const ADMIN_CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'

export const ADMIN_CATEGORY_DELETE_SUCCESS = 'ADMIN_CATEGORY_DELETE_SUCCESS'
export const ADMIN_CATEGORY_DELETE_FAIL = 'ADMIN_CATEGORY_DELETE_FAIL'

export const ADMIN_ENABLE_CATEGORY_LISTING_SUCCESS = 'ADMIN_ENABLE_CATEGORY_LISTING_SUCCESS'
export const ADMIN_ENABLE_CATEGORY_LISTING_FAIL = 'ADMIN_ENABLE_CATEGORY_LISTING_FAIL'

// Sub Category
export const ADMIN_SUBCATEGORY_LISTING_SUCCESS = 'ADMIN_SUBCATEGORY_LISTING_SUCCESS'
export const ADMIN_SUBCATEGORY_LISTING_FAIL = 'ADMIN_SUBCATEGORY_LISTING_FAIL'

export const ADMIN_SUBCATEGORY_ADD_SUCCESS = 'ADMIN_SUBCATEGORY_ADD_SUCCESS'
export const ADMIN_SUBCATEGORY_ADD_FAIL = 'ADMIN_SUBCATEGORY_ADD_FAIL'

export const ADMIN_SUBCATEGORY_EDIT_SUCCESS = 'ADMIN_SUBCATEGORY_EDIT_SUCCESS'
export const ADMIN_SUBCATEGORY_EDIT_FAIL = 'ADMIN_SUBCATEGORY_EDIT_FAIL'

export const ADMIN_SUBCATEGORY_UPDATE_SUCCESS = 'ADMIN_SUBCATEGORY_UPDATE_SUCCESS'
export const ADMIN_SUBCATEGORY_UPDATE_FAIL = 'ADMIN_SUBCATEGORY_UPDATE_FAIL'

export const ADMIN_SUBCATEGORY_DELETE_SUCCESS = 'ADMIN_SUBCATEGORY_DELETE_SUCCESS'
export const ADMIN_SUBCATEGORY_DELETE_FAIL = 'ADMIN_SUBCATEGORY_DELETE_FAIL'

export const ADMIN_WISE_SUBCATEGORY_LISTING_SUCCESS = 'ADMIN_WISE_SUBCATEGORY_LISTING_SUCCESS'
export const ADMIN_WISE_SUBCATEGORY_LISTING_FAIL = 'ADMIN_WISE_SUBCATEGORY_LISTING_FAIL'

// Service
export const ADMIN_SERVICE_LISTING_SUCCESS = 'ADMIN_SERVICE_LISTING_SUCCESS'
export const ADMIN_SERVICE_LISTING_FAIL = 'ADMIN_SERVICE_LISTING_FAIL'

export const ADMIN_SERVICE_ADD_SUCCESS = 'ADMIN_SERVICE_ADD_SUCCESS'
export const ADMIN_SERVICE_ADD_FAIL = 'ADMIN_SERVICE_ADD_FAIL'

export const ADMIN_SERVICE_EDIT_SUCCESS = 'ADMIN_SERVICE_EDIT_SUCCESS'
export const ADMIN_SERVICE_EDIT_FAIL = 'ADMIN_SERVICE_EDIT_FAIL'

export const ADMIN_SERVICE_UPDATE_SUCCESS = 'ADMIN_SERVICE_UPDATE_SUCCESS'
export const ADMIN_SERVICE_UPDATE_FAIL = 'ADMIN_SERVICE_UPDATE_FAIL'

export const ADMIN_SERVICE_DELETE_SUCCESS = 'ADMIN_SERVICE_DELETE_SUCCESS'
export const ADMIN_SERVICE_DELETE_FAIL = 'ADMIN_SERVICE_DELETE_FAIL'

export const ADMIN_ENABLE_SERVICE_LISTING_SUCCESS = 'ADMIN_ENABLE_SERVICE_LISTING_SUCCESS'
export const ADMIN_ENABLE_SERVICE_LISTING_FAIL = 'ADMIN_ENABLE_SERVICE_LISTING_FAIL'

// State
export const ADMIN_STATE_LISTING_SUCCESS = 'ADMIN_STATE_LISTING_SUCCESS'
export const ADMIN_STATE_LISTING_FAIL = 'ADMIN_STATE_LISTING_FAIL'

export const ADMIN_STATE_ADD_SUCCESS = 'ADMIN_STATE_ADD_SUCCESS'
export const ADMIN_STATE_ADD_FAIL = 'ADMIN_STATE_ADD_FAIL'

export const ADMIN_STATE_EDIT_SUCCESS = 'ADMIN_STATE_EDIT_SUCCESS'
export const ADMIN_STATE_EDIT_FAIL = 'ADMIN_STATE_EDIT_FAIL'

export const ADMIN_STATE_UPDATE_SUCCESS = 'STATE_UPDATE_SUCCESS'
export const ADMIN_STATE_UPDATE_FAIL = 'STATE_UPDATE_FAIL'

export const ADMIN_STATE_DELETE_SUCCESS = 'ADMIN_STATE_DELETE_SUCCESS'
export const ADMIN_STATE_DELETE_FAIL = 'ADMIN_STATE_DELETE_FAIL'

// City
export const ADMIN_CITY_LISTING_SUCCESS = 'ADMIN_CITY_LISTING_SUCCESS'
export const ADMIN_CITY_LISTING_FAIL = 'ADMIN_CITY_LISTING_FAIL'

export const ADMIN_CITY_ADD_SUCCESS = 'ADMIN_CITY_ADD_SUCCESS'
export const ADMIN_CITY_ADD_FAIL = 'ADMIN_CITY_ADD_FAIL'

export const ADMIN_CITY_EDIT_SUCCESS = 'ADMIN_CITY_EDIT_SUCCESS'
export const ADMIN_CITY_EDIT_FAIL = 'ADMIN_CITY_EDIT_FAIL'

export const ADMIN_CITY_UPDATE_SUCCESS = 'CITY_UPDATE_SUCCESS'
export const ADMIN_CITY_UPDATE_FAIL = 'CITY_UPDATE_FAIL'

export const ADMIN_CITY_DELETE_SUCCESS = 'ADMIN_CITY_DELETE_SUCCESS'
export const ADMIN_CITY_DELETE_FAIL = 'ADMIN_CITY_DELETE_FAIL'

// Customer FAQ
export const ADMIN_CUSTOMER_FAQ_LISTING_SUCCESS = 'ADMIN_CUSTOMER_FAQ_LISTING_SUCCESS'
export const ADMIN_CUSTOMER_FAQ_LISTING_FAIL = 'ADMIN_CUSTOMER_FAQ_LISTING_FAIL'

export const ADMIN_CUSTOMER_FAQ_ADD_SUCCESS = 'ADMIN_CUSTOMER_FAQ_ADD_SUCCESS'
export const ADMIN_CUSTOMER_FAQ_ADD_FAIL = 'ADMIN_CUSTOMER_FAQ_ADD_FAIL'

export const ADMIN_CUSTOMER_FAQ_EDIT_SUCCESS = 'ADMIN_CUSTOMER_FAQ_EDIT_SUCCESS'
export const ADMIN_CUSTOMER_FAQ_EDIT_FAIL = 'ADMIN_CUSTOMER_FAQ_EDIT_FAIL'

export const ADMIN_CUSTOMER_FAQ_UPDATE_SUCCESS = 'CUSTOMER_FAQ_UPDATE_SUCCESS'
export const ADMIN_CUSTOMER_FAQ_UPDATE_FAIL = 'CUSTOMER_FAQ_UPDATE_FAIL'

export const ADMIN_CUSTOMER_FAQ_DELETE_SUCCESS = 'ADMIN_CUSTOMER_FAQ_DELETE_SUCCESS'
export const ADMIN_CUSTOMER_FAQ_DELETE_FAIL = 'ADMIN_CUSTOMER_FAQ_DELETE_FAIL'

// Why Choose us
export const ADMIN_WHY_CHOOSE_US_LISTING_SUCCESS = 'ADMIN_WHY_CHOOSE_US_LISTING_SUCCESS'
export const ADMIN_WHY_CHOOSE_US_LISTING_FAIL = 'ADMIN_WHY_CHOOSE_US_LISTING_FAIL'

export const ADMIN_WHY_CHOOSE_US_ADD_SUCCESS = 'ADMIN_WHY_CHOOSE_US_ADD_SUCCESS'
export const ADMIN_WHY_CHOOSE_US_ADD_FAIL = 'ADMIN_WHY_CHOOSE_US_ADD_FAIL'

export const ADMIN_WHY_CHOOSE_US_EDIT_SUCCESS = 'ADMIN_WHY_CHOOSE_US_EDIT_SUCCESS'
export const ADMIN_WHY_CHOOSE_US_EDIT_FAIL = 'ADMIN_WHY_CHOOSE_US_EDIT_FAIL'

export const ADMIN_WHY_CHOOSE_US_UPDATE_SUCCESS = 'WHY_CHOOSE_US_UPDATE_SUCCESS'
export const ADMIN_WHY_CHOOSE_US_UPDATE_FAIL = 'WHY_CHOOSE_US_UPDATE_FAIL'

export const ADMIN_WHY_CHOOSE_US_DELETE_SUCCESS = 'ADMIN_WHY_CHOOSE_US_DELETE_SUCCESS'
export const ADMIN_WHY_CHOOSE_US_DELETE_FAIL = 'ADMIN_WHY_CHOOSE_US_DELETE_FAIL'


//Profile
export const ADMIN_PROFILE_EDIT_SUCCESS = 'ADMIN_PROFILE_EDIT_SUCCESS'
export const ADMIN_PROFILE_EDIT_FAIL = 'ADMIN_PROFILE_EDIT_FAIL'

export const ADMIN_PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const ADMIN_PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'